# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|

  config.vm.provider "virtualbox" do |v|
    v.name = "mask_detector"
    v.memory = 16384
    v.cpus = 6
    v.gui = false
  end

  config.vm.hostname = "opencv"
  config.vm.box = "ubuntu/bionic64"
  config.vm.network "private_network", type: "dhcp"
  config.vm.provision "shell", path: "bootstrap.sh"
  config.vm.disksize.size = "5GB"
end
