# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|

  config.vm.provider "virtualbox" do |v|
    v.name = "pm_k8s_service"
    v.memory = 16384
    v.cpus = 6
    v.gui = false
  end

  config.vm.hostname = "microk8s"
  config.vm.box = "ubuntu/bionic64"
  config.vm.network "private_network", type: "dhcp"
  config.vm.provision "shell", path: "bootstrap.sh"
  config.vm.provision "shell", path: "k8s_install.sh"
end

