# Use an official Python runtime as a parent image
FROM camo6016/maskdetector

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt

# Run app.py when the container launches
CMD ["python3", "WebTest.py"]
