apiVersion: v1
kind: Service
metadata:
  name: {{ include "md_chart.fullname" . }}
  labels:
{{ include "md_chart.labels" . | indent 4 }}

  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"

spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    app/name: {{ include "md_chart.name" . }}
    app/instance: {{ .Release.Name }}
